### ISSUE TITLE
Validate `ctypes_use` for existing cell types

### ISSUE THREAD

**Issue by VPetukhov** [kharchenkolab/scITD#14]
Hi Jonathan,
This is a tiny issue: if there is a typo in cell type name for `ctypes_use`, the call to `form_tensor` fails without much information as it filters all samples because none of them has the one with the typo. Would be cool to validate the values for `ctypes_use`.

**Comment by j-mitchel** [comment]
Ah good catch - I'll add a check to ensure the cell type names are present in the metadata
