### ISSUE TITLE
An error message with “run_gsea_one_factor” function 

### ISSUE THREAD

**Issue by zyb1984** [kharchenkolab/scITD#17]
When I tried to follow the Walkthrough “http://pklab.med.harvard.edu/jonathan/ ” , an errow reported with “run_gsea_one_factor” function, and error message with “Error in preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam,  : Not all stats values are finite numbers”
   Then I tried to check the original code of “run_gsea_one_factor” function, but when the enrichment method arguments were set with "fgsea", all was ok, But when the enrichment method arguments were set with "hypergeometric",  an error message had reported, and with “Error in reshape_loadings(sr_col, genes, ctypes) : with no"reshape_loadings" function”. So, I tried to check the "reshape_loadings" function, I found no information with this "reshape_loadings" function, Could you help me with some information or suggestion about the "reshape_loadings" function? 
  With session info()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     other attached packages:
[1] scITD_1.0.2  Matrix_1.5-3
     And the scITD package was installed through CRAN.

**Comment by j-mitchel** [comment]
Thanks for using scITD. 

I just retested the walkthrough and it still seems to be working. Can you confirm if you're running it with the example data or your own dataset and whether you're using the Github version or the CRAN version of the package?

The reshape_loadings() function can be found in the plot_tucker.R file. This function is internal (not exported), but should be accessible to the other functions in the package, so I wonder if this has to do with how you installed/load the package.

**Comment by zyb1984** [comment]
Thanks for your reply
    I ran the  Walkthrough with the example data, and I had solved this problem. This error message was caused by some NA value in the results of "get transformed expression for each gene by summing d_score * scaled exp", and I fixed the function of run_fgsea with add "exp_vals <- exp_vals [is.finite(exp_vals)] "

**Comment by csangara** [comment]
Seconding that I also had to use the fix of @zyb1984 the be able to run the example walkthrough. I tried both the CRAN and GitHub version and both needed the fix. My `sessionInfo()`:

```
R version 4.3.1 (2023-06-16)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Stream 8

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblaso-r0.3.15.so;  LAPACK version 3.9.0

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] scITD_1.0.3  Matrix_1.6-1

```

**Comment by j-mitchel** [comment]
Thank you for pointing this out! I was using an older version of fgsea that does not error when there are some NaN values included. The NaN genes you remove with `exp_vals <- exp_vals [is.finite(exp_vals)]` are simply ones that had 0 expression in all donors, as the `scale()` function gives NaN when there is zero variance. Therefore, this correction is totally fine to do and I'll go ahead and update this in the package asap.
