### ISSUE TITLE
Package maintenance

### ISSUE THREAD

**Issue by evanbiederstedt** [kharchenkolab/scITD#2]
A few things to work on/consider, some of these motivated by potential CRAN comments:

- [x] Please change any `=T` and `=F` into `TRUE` and `FALSE`
- [x] Please add a few more sentences to the DESCRIPTION, and link to a paper perhaps
- [x] Vignettes should run on "small" data
- [x] I think all functions should be documented, but especially ones exported. You will need:

    - param: datatype Explanation here (default=xx)
    - return 
    - example

I'm happy to help out :)

**Comment by evanbiederstedt** [comment]
When created the datasets in `/data`, please create a script which replicates how this data was generated for others. This is exceptionally important for reproducibility. Here's an example: https://github.com/kharchenkolab/sccore/tree/master/data-raw

Please this script (and any associated files) in `/data-raw`. 

Let me know if you need help

Thanks, Evan

**Comment by j-mitchel** [comment]
Just added the raw data preprocessing file in /data-raw and the raw data itself in the /inst/extdata directory

**Comment by evanbiederstedt** [comment]
CRAN won't allow 431 MB within `/inst/extdata/`, so we'll have to probably host that on a website too :)

`genes.tsv` probably should be in `/inst/extdata/`, not in `/data`---if you wish to automatically load it, please make it an `.RData`

Some changes from me:
--- added `Depends: R (>= 3.5.0)` as that's the version of R needed for the compression we're using
--- resaved the *RData files to use `compress="xz"`, as that's a better compression standard.

**Comment by evanbiederstedt** [comment]
CC @j-mitchel 

For the functions, we'll need examples. It may not be possible for all of them, but it would be good to have for the majority. 

Also, I added a template for tests, which are useful. I'd recommend just basic unit tests to make sure functions work; I did something similar for sccore: 

https://github.com/kharchenkolab/sccore/blob/master/tests/testthat/test_helpers.R

If you write up some examples with the functions in the roxygen2 documentation, I'm happy to help out with testing.

**Comment by evanbiederstedt** [comment]
Hi @j-mitchel 

For CRAN, we will need examples for the majority of the functions. Normally I create mini-examples in the roxygen2 comments, and then use this as a test for predicted behavior. 

I think that's the last thing needed to truly finish the package.
