### ISSUE TITLE
'sva' dependency is not available when installing from CRAN

### ISSUE THREAD

**Issue by VPetukhov** [kharchenkolab/scITD#20]
Installation with `install.packages('scITD')` fails with `ERROR: dependency ‘sva’ is not available for package ‘scITD’`. R version 4.2.3.

Running `BiocManager::install("sva")` solves the problem. Perhaps, we should add it to the README.

**Comment by j-mitchel** [comment]
Just updated the readme to include this and other bioconductor based dependencies, thanks!
