### ISSUE TITLE
get_one_factor_gene_pvals function is absent in CRAN version of package

### ISSUE THREAD

**Issue by StanislavBratchikov** [kharchenkolab/scITD#21]
Hey, I was trying to run the walkthrough available in GitHub ReadMe. However I wasn't able to find get_one_factor_gene_pvals function to run this line` f1_pvals <- get_one_factor_gene_pvals(pbmc_container, factor_select=1)`. It seemed to be absent in package when I was skimming through available methods.

**Comment by j-mitchel** [comment]
I believe it is currently only available from the github version of the package, but will be included in our next CRAN update. To use it now, you can install scITD with:
devtools::install_github("kharchenkolab/scITD")

Alternatively, you can find the code for this function from the run_jackstraw.R file.

**Comment by StanislavBratchikov** [comment]
Great! Thank you!
