### ISSUE TITLE
Some functions do not work when cell types contain special characters

### ISSUE THREAD

**Issue by csangara** [kharchenkolab/scITD#22]
I don't think I saw this mentioned in the vignette, but cell type names at the very least cannot contain `.` and `_` to be able to run the  vignettes.

Having a `.` in the name will throw the following error in `get_all_lds_factor_plots`:
```
Error in sig_df[rownames(tmp_casted_num), colnames(tmp_casted_num)] : 
  subscript out of bounds
```

And having a `_` in the name will throw the following error in `compute_LR_interact`:
```
Error in `[<-`(`*tmp*`, lig_ct_rec, mod_nm, value = myres2[lig_source_target_mod]) : 
  subscript out of bounds
```

**Comment by j-mitchel** [comment]
Thanks for identifying this error case. I just added a warning during container initialization when problematic special characters in the cell type names. It will now automatically remove those special characters and concatenate the names.
