### ISSUE TITLE
Error in render_multi_plots

### ISSUE THREAD

**Issue by balthasar0810** [kharchenkolab/scITD#24]
Hi! I am trying to reproduce the walkthrough.

After the last line:
pbmc_container <- get_all_lds_factor_plots(pbmc_container, 
                                           use_sig_only=TRUE,
                                           nonsig_to_zero=TRUE,
                                           sig_thresh=.02,
                                           display_genes=FALSE,
                                           gene_callouts = TRUE,
                                           callout_n_gene_per_ctype=3,
                                           show_var_explained = TRUE)

# arrange the plots into a figure and show the figure
myfig <- render_multi_plots(pbmc_container,data_type='loadings')
myfig

Getting this error:
Error in .local(object, ...) : 
  unused argument (legend_grouping = "original")

This looks like an internal thing, can someone help?

Thansk!

**Comment by balthasar0810** [comment]
I guess the error comes from this line in render_multi_plots in the package:
gb <- grid::grid.grabExpr(draw(hm_list[[i]], annotation_legend_list = hm_legends[[i]], 
        legend_grouping = "original", newpage = FALSE))

This might be an issue with ComplexHeatmap. Any advice?

**Comment by balthasar0810** [comment]
I guess the error comes from this line in render_multi_plots in the package:
gb <- grid::grid.grabExpr(draw(hm_list[[i]], annotation_legend_list = hm_legends[[i]], 
        legend_grouping = "original", newpage = FALSE))

This might be an issue with ComplexHeatmap. Any advice?

**Comment by j-mitchel** [comment]
Hi, thanks for using scITD! It still seems to work fine on my machine. The version of ComplexHeatmap I have installed is ComplexHeatmap_2.14.0 and in the ComplexHeatmap pdf manual of their newest versions it looks like 'legend_grouping' is still a parameter for their draw() function. I'd just try updating that package (maybe try both bioconductor version as well as their github version of that package). 

If all else fails, you can generate the loadings plots for individual factors using the plot_loadings_annot() function like this:
pbmc_container <- plot_loadings_annot(pbmc_container, factor_select = 1,
                                      use_sig_only=TRUE,
                                      nonsig_to_zero=TRUE,
                                      sig_thresh=.02,
                                      display_genes=FALSE,
                                      gene_callouts = TRUE,
                                      callout_n_gene_per_ctype=3,
                                      show_var_explained = TRUE)

**Comment by balthasar0810** [comment]
Thanks, this solved the issue. Install ComplexHeatmap from Github
